db:
  url: jdbc:log4jdbc:mariadb://localhost:3306/watcher
  #url: jdbc:log4jdbc:mariadb://192.168.0.5:3306/watcher
  username: WATCHER
  password: dkwjTl0904!
  driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy

logging:
  config: classpath:watcher-logback.xml


spring:
  session:
    store-type: redis
  redis:
    host: localhost
    port: 6379

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  profiles:
    active: local






