server_domain: ${WATCHER_DOMAIN}

naver:
  client:
    id: r_P2RApQNgYR3fttFpHz
    secret: kc57YTY7h0

cors:
  origin: ${WATCHER_CORS_ORIGIN}
  method: GET,POST,PUT,DELETE

spring:
  config:
    activate:
      on-profile: prod

  servlet:
    multipart:
      enabled: true
      location: /home/ec2-user/watcher/upload
      max-file-size: 128MB
      max-request-size: 128MB

  session:
    store-type: redis
  redis:
    host: localhost
    port: 6379

upload:
  root: /home/ec2-user
  path: /watcher/upload

db:
  url: jdbc:log4jdbc:mariadb://watcher-db.caopszgvg30l.ap-northeast-2.rds.amazonaws.com:3306/watcher
  #url: jdbc:log4jdbc:mariadb://192.168.0.5:3306/watcher
  username: watcher-user-01
  password: dkwjTl0904!
  driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy

server:
  port: 8081

logging:
  config: classpath:watcher-prod-logback.xml
  file:
    name: catalina
    path: ${WATCHER_WAS_LOG}