server_domain: localhost

naver:
  client:
    id: ThouS3nsCEwGnhkMwI1I
    secret: nWJxzTmxwr

cors:
  origin: http://localhost:8080
  method: GET,POST,PUT,DELETE

spring:
  config:
    activate:
      on-profile: dev

  servlet:
    multipart:
      enabled: true
      location: D://watcher/upload
      max-file-size: 128MB
      max-request-size: 128MB

  session:
    store-type: redis
  redis:
    host: localhost
    port: 6379

#사용자 정의
upload:
  root: D://
  path: /watcher/upload

db:
  url: jdbc:log4jdbc:mariadb://localhost:3306/watcher
  #url: jdbc:log4jdbc:mariadb://192.168.0.5:3306/watcher
  username: WATCHER
  password: dkwjTl0904!
  driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy

server:
  port: 8081

logging:
  config: classpath:watcher-dev-logback.xml
  file:
    name: catalina
    path: /watcher/logs


